import requests
from bs4 import BeautifulSoup
from datetime import datetime
from urllib.parse import urljoin

from app.models import NewsArticle


class HTMLCollector:

    def __init__(self, url: str, source: str):
        self.url = url
        self.source = source

    def collect(self):

        response = requests.get(
            self.url,
            timeout=10,
            headers={
                "User-Agent": "Mozilla/5.0"
            }
        )

        response.raise_for_status()

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        articles = []

        # Try multiple wrappers because each site has different HTML structure.
        candidates = soup.find_all(["article", "li", "div"])

        for item in candidates:

            link = item.find("a", href=True)

            if not link:
                continue

            title = ""
            title_element = item.find(
                ["h1", "h2", "h3", "span"],
                class_=lambda x: x and "title" in x
            )
            if title_element:
                title = title_element.get_text(strip=True)
            if not title:
                title = link.get_text(strip=True)

            if len(title) < 8:
                continue

            url = link.get("href")
            if not url:
                continue
            url = urljoin(self.url, url)

            date_element = item.find("time")
            published = datetime.now()

            if date_element and date_element.get_text(strip=True):
                for pattern in ("%b %d, %Y", "%Y-%m-%d", "%d %b %Y"):
                    try:
                        published = datetime.strptime(
                            date_element.get_text(strip=True),
                            pattern,
                        )
                        break
                    except ValueError:
                        continue

            articles.append(
                NewsArticle(
                    title=title,
                    url=url,
                    summary="",
                    published=published,
                    source=self.source,
                )
            )

        # Remove duplicates generated by broad candidate selection.
        unique_articles = {article.url: article for article in articles}
        return list(unique_articles.values())